FROM python:3.11-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

ENV PORT=7860
ENV DEBUG=false
ENV ALLOWED_HOSTS=*
ENV CORS_ALLOWED_ORIGINS=https://rahulagg1804.github.io
ENV GEOCODING_ENABLED=true

EXPOSE 7860

CMD gunicorn config.wsgi:application --bind 0.0.0.0:7860 --timeout 120 --workers 1
